name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rename CV file
        run: mv cv.pdf index.pdf

      - name: Install pdf2htmlEX
        run: |
          sudo apt update
          sudo apt install -y libfontconfig1 libcairo2 libjpeg-turbo8
          sudo apt --fix-broken install
          wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb
          sudo mv pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb pdf2htmlEX.deb
          sudo dpkg -i ./pdf2htmlEX.deb

      - name: Convert PDF to HTML
        run: pdf2htmlEX --process-outline 1 --fallback 1 --bg-format svg --zoom 1.3 --process-type3 1 --dest-dir out index.pdf

      - name: Publish the web pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
