name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rename
        run: mv cv.tex index.tex

      - name: Run make4ht
        uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -u -d out index.tex"

      - name: Publish the web pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
